spring.application.name=fixmate-backend
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/fixmate_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:computer}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

app.jwt.secret=${JWT_SECRET:FixMateSuperSecretKey2026SecureKey123}
app.jwt.expiration-ms=86400000

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,https://fixmate-s4.vercel.app}